MATLAB = /usr/local/MATLAB/R2017a/bin/matlab
ARG    = -nodisplay -nosplash -nodesktop

clean:
	rm -rf ../sourcedata
	rm -rf ../*.tsv
	rm -rf ../*.json

sourcedata:
	$(MATLAB) $(ARG) -r "run('spm_01_download_ds');exit;"

bids: sourcedata
	$(MATLAB) $(ARG) -r "run('spm_02_convert.m');exit;"
